[window]
Width = 400
Height = 400

Scaling = 2
FrameSkip = 100
DrawAgents = true

SplashText = "S.P.I.S. - Country Roads since 2023"

[parameters]
DecayRate = 0.9

AgentCount = 2000
AgentSpeed = 1.0

SensorAngle = 1.17
SensorDistance = 10.0
SensorSize = 1.0

SporeWeight = 1.0
SolfluxWeight = 700.0
HeightWeight = 0.5
