[window]
Width = 400
Height = 400

Scaling = 2
FrameSkip = 50
DrawAgents = true

SplashText = "S.P.I.S. - Country Roads since 2023"

[parameters]
DecayRate = 0.9

AgentCount = 2000
AgentSpeed = 1.0
AgentSolflux = 5.0

NodeCount = 8
NodeSolflux = 50.0

SensorAngle = 1.17
SensorDistance = 8.0
SensorSize = 1.0

KernelRadius = 5
SolfluxWeight = 1.0
HeightWeight = 0.5
