[window]
WindowSize = 800
Size = 400
Resolution = 4

FrameSkip = 10
DrawAgents = true

SplashText = "S.P.I.S. - Country Roads since 2023"

[parameters]
PheremoneDecayRate = 0.93

AgentCount = 20000
AgentSpeed = 1.0
AgentSensorAngle = 1.4
AgentSensorDistance = 10.0
AgentSensorSize = 1.0

PheremoneWeight = 1.0
HeightWeight = 0.5
